steps:

- name: 'gcr.io/cloud-builders/gke-deploy'
  id: Write Datafix branch
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    podname=$(echo ${_HEAD_BRANCH} | tr '[:upper:]' '[:lower:]')
    sed -i "s/BRANCH_NAME/$podname/g" manifests/2-pod.yaml
    sed -i "s/$PROJECT_ID/${PROJECT_ID}/g" manifests/1-serviceAccount.yaml
    sed -i "s/$PROJECT_NUMBER/${PROJECT_NUMBER}/g" manifests/0-provider.yaml
 
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=manifests/
  - --location=europe-west1
  - --namespace=${_NAMESPACE}
  - --cluster=${PROJECT_ID}-cluster
  timeout: 600s
