apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-secret-provider
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/$PROJECT_NUMBER/secrets/postman-config-secret/versions/latest"
        path: "env.json"