apiVersion: v1
kind: ServiceAccount
metadata:
  name: postman-runner-serviceaccount
  namespace: dft-nap-dev
  annotations:
    iam.gke.io/gcp-service-account: gke-workload@dft-rsss-findtransptdata-dev.iam.gserviceaccount.com
---
apiVersion: v1
kind: Pod
metadata:
  name: postman-runner-BRANCH_NAME
  namespace: dft-nap-dev
spec:
  serviceAccountName: postman-runner-serviceaccount
  containers:
  - name: postman-runner
    image: postman/newman
    command: ["newman"]
    args: ["run","https://www.getpostman.com/collections/7ec2b48f6b5af89ca37a","-e","/srv/config/env.json","--insecure", "--verbose"]
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
    - name: postman-config-secret
      mountPath: "/srv/config"
      readOnly: true
  restartPolicy: Never
  volumes:
    - name: postman-config-secret
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "gcp-secret-provider"
  