apiVersion: v1
kind: ServiceAccount
metadata:
  name: postman-runner-serviceaccount
  namespace: dft-nap-dev
  annotations:
    iam.gke.io/gcp-service-account: gke-workload@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: Pod
metadata:
  name: postman-runner-BRANCH_NAME
  namespace: dft-nap-dev
spec:
  serviceAccountName: postman-runner-serviceaccount
  containers:
  - name: postman-runner
    image: postman/newman
    command: ["newman"]
    args: ["run","https://api.postman.com/collections/21262774-1bc663de-38ac-4bbd-9711-433d9940d0d5?access_key=PMAT-01GTEWV7C2WX3HNHCJSH18NK7Z","-e","/srv/config/env.json","--insecure"]
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
    - name: postman-config-secret
      mountPath: "/srv/config"
      readOnly: true
  restartPolicy: Never
  volumes:
    - name: postman-config-secret
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "gcp-secret-provider"

  