apiVersion: v1
kind: Pod
metadata:
  name: postman-runner-BRANCH_NAME
  namespace: dft-nap-dev
spec:
  containers:
  - name: postman-runner
    image: europe-docker.pkg.dev/dft-rsss-findtransptdata-dev/dft-nap/postmanrunner
    command: ["newman"]
    args: ["run","https://www.getpostman.com/collections/7ec2b48f6b5af89ca37a","-e","/srv/env.json","--insecure"]
  restartPolicy: Never
  